### ISSUE TITLE
Not downloading all files

### ISSUE THREAD

**Issue by mojamuto** [Dineshkarthik/telegram_media_downloader#147]
**Describe the bug**
I have a channel with 2108 documents to download, I run the script and it downloads 1100 documents and finishes.
I delete the downloaded documents folder and run the clean script again, and it downloads 910 documents and finishes.
I run the script again in clean and it downloads 930 documents and finishes.

**To Reproduce**
Share the config: `Please don't share your api_hash & api_id`
```api_hash:
api_id:
chat_id: -1001377813744
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry: []
last_read_message_id: 0
media_types:
- document
```

**Python Version**
Python 3.10.2

**OS:**
OS: Void Linux
KERNEL: Linux 5.15.17_1

**Logs**
Logs showing the exception

**Additional context**
config.yaml file when finished 

```api_hash:
api_id:
chat_id: -1001377813744
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry: []
last_read_message_id: 4274
media_types:
- document
```

**Comment by Dineshkarthik** [comment]
Hi,
This is a known issue, if you see the message id of files which are not downloaded due to timeout or network error will be added to the config.yaml under `ids_to_retry`. There is an ongoing feature in roadmap #65 to make use of these ids and download the files which are added to the retry list. Hope I will get time to add this feature sooner.

**Comment by mojamuto** [comment]
when I saw in the configuration file ids_to_retry: [] I assumed that I was implementing , sorry for not being able to read well :/

Thank you very much for the clarification and for the program.
