### ISSUE TITLE
The number of files after the download is complete does not match the number of files in the channel

### ISSUE THREAD

**Issue by 2284787774** [Dineshkarthik/telegram_media_downloader#176]
**Is your feature request related to a problem? Please describe.**
The number of files after the download is complete does not match the number of files in the channel

**Describe the solution you'd like**
Add a checksum to the file, which can be compared with the channel's files and which files have not been downloaded and re-downloaded

**Describe alternatives you've considered**

**Additional context**
https://s3.bmp.ovh/imgs/2022/02/75e70891d1e26e22.png

**Comment by Dineshkarthik** [comment]
Hi,

The reason why the numbers doesn't match is mostly due to duplicate files. Telegram-media-dpwnloader compares the md5 hash of the already downloaded files vs newly downloaded files to avoid duplicates. Consider if there is a same file which is shared 5 times in the channel the downloader script will have only one copy of the file downloaded not 5 duplicate copies.


Also when a download is failed it, the message it is added to the - `ids_to_retry` list in the config.yaml and will be re-downloaded when the re-download feature is added to the telegram-media-downloader which is in the roadmap #65 

You can see the number of files which are not downloaded and the feature will be introduced soon in the logs.

![Screenshot 2022-02-28 at 10 15 10 AM](https://user-images.githubusercontent.com/7752572/155956373-14bcbf5a-cd13-46af-9f59-9149d6c1e319.png)
